### ISSUE TITLE
How can I programmatically acquire some tokens using standard Linux CLI tools?

### ISSUE THREAD

**Issue by bitcoinmeetups** [tracer-protocol/perpetual-pools-contracts#175]
Hello,

I'm MB. A very nice and polite guy.

How can I programmatically acquire some tokens using standard Linux CLI tools?

**Comment by mynameuhh** [comment]
You will need to call `PoolCommitter::commit` with the relevant data. For example, if you wanted to mint $1000 worth of long tokens, you would want to call `commit(2, 1000*10**6)`. `2` is the `CommitType` for `LONG_MINT`, and `1000*10**6` is 1000 USDC.

**Comment by mynameuhh** [comment]
Another way would be to interact with the Balancer pools, but that is a question for the balancer team!
