### ISSUE TITLE
Minting and burning fee

### ISSUE THREAD

**Issue by mynameuhh** [tracer-protocol/perpetual-pools-contracts#202]
**Overview**

- Within V2, there will need to be a fee charged both the action of minting and burning. In other words, users will be charged a fee at the time of minting tokens, and also at the time of burning tokens.
- The fee will be a percentage. e.g. 1%. It should be a configurable parameter. The fee should be able to be changed by the contract owner after the time of deployment.
- The fee rate for minting will not necessarily be the same as the fee rate for burning.
- The proceeds of the fee will be added to the pool at which the user was minting into (or burning from).

---

**Minting Fee Logic**

- Hypothetically, let's say the mint fee rate is 1%.
- A user, Bob, commits to minting 100 USDC.
- At the time of committing to mint, 1 USDC will be taken away from the user, Bob. It is 1 USDC because it's 100 USDC * 1%.
- Bob's commit is now only 99 USDC. This will proceed as normal, and will mint tokens at the fair price.

Dev notes:
- In the above example, The user commits 100 Usdc, all 100 are transferred to the pool, but the amount of tokens stored as part of the commit would be 99, so when they go to claim, they will only get that 99 usdc worth of tokens.

---

**Burning Fee Logic**

- Hypothetically, let's say the burn fee rate is 2%.
- A user, Bob, has commited to burn his 200 Long Pool tokens.
- The 200 long pool tokens will sit in the shadow pool until the wait time is up.
- At the rebalancing event in which the commit will be executed, the SC should calculate the value of the 200 long pool tokens (e.g. if price is $2, then the overall value is $400).
- From this, the Smart contract takes $8 ($400 * 2%) from the user, and adds it back into the pool from which it was taken. All the users pool tokens are destroyed.
- 98% of the value is sent to the user.

---

### Extra notes

- Burning fees will require storing the fee rate at in a given update interval (since fee rate can change at any time) and using that to calculate how much quote token a user is entitled to during `updateAggregateBalance`

---

### Completion criteria (added by devs)
Where `n` is the fee rate as a percentage (`n == 1` means fee is 1%)
- When a user mints, `100 - n%` of the settlement tokens they minted with is stored in the user's commitment data.
- When a user mints then claims after update interval, the pool should still be in ownership of `n%` of the original commitment amount of settlement tokens.
- When a user mints, `n%` of the settlement tokens they minted with should be added to the balance of the side to which they are minting.
    - e.g. if they mint $100 to the LONG side, with a 1% fee, directly after minting, $1 should be added to `LeveragedPool::longBalance`
- When a user burns, `100 - n%` of the settlement tokens they would normally be entitled to are in the user's aggregate balance after the update interval passes.
- When a user burns, upkeep happens, then they update their balance (usually through claiming), n% of the settlement tokens they gained should be kept in the pool and that amount added to the correct side of the pool (either `longBalance` or `shortBalance`)
- The same as above, but with `100 - n%` of the settlement tokens deposited to the user's wallet after claiming.
- If `n == 0`, then the user should get the exact amount they would be entitled to before the changes of this PR were implemented

**Comment by nisdo** [comment]
This is a relatively large logic change, would require a bit of new things to be stored in aggregate balance. Owner of this task would need to define further here the "done" steps.
