### ISSUE TITLE
Write up enforced structure of test suite

### ISSUE THREAD

**Issue by mynameuhh** [tracer-protocol/perpetual-pools-contracts#208]
- Currently the test suit is disorganised.
- We need to settle on a rigorous way to organise and structure the test.
- We then need to refactor tests (not part of this ticket)
- We then need to collectively enforce it

**Comment by mynameuhh** [comment]
I think @sporejack is best suited for this.

**Comment by nisdo** [comment]
To be added as a markdown file inside the appropriate test directory

**Comment by nisdo** [comment]
How we define this task is done: 
- Markdown file created inside of test folder containing
-- How to add new tests
-- Justification for why
-- Should define what the test suite should look like

**Comment by mynameuhh** [comment]
next steps:
- Merge
