### ISSUE TITLE
Update deployment logic

### ISSUE THREAD

**Issue by sporejack** [tracer-protocol/perpetual-pools-contracts#222]
The codebase has undergone a series of significant changes since the [deployment logic](https://github.com/tracer-protocol/perpetual-pools-contracts/tree/0282b6b4a0ad97c69153d19cca97fa93b3539af7/deploy) was last modified. For obvious reasons, the ability to deploy the entire set of contracts to a testnet (Arbitrum Rinkeby or even Kovan) is crucial and will likely become a pressing matter very soon.

**Comment by Paul4912** [comment]
Should we seperate this into update deployment logic as 1 ticket and deploy on testnet as another. Thing is deploying might make it so we find more fixes in deployment logic. But not separating it will make ticket very big.
