### ISSUE TITLE
Review 0xCurry's indicies PR

### ISSUE THREAD

**Issue by mynameuhh** [tracer-protocol/perpetual-pools-contracts#226]
Exists in an internal/private repo.

I made a ticket for this because it is quite a big PR. Otherwise I likely would have just done it quickly without worrying about fitting it in to a sprint.

Reviewers (Last one to tick can add to "Done". To add confirmed reviewers during either retro or sprint planning.)
- [x] @mynameuhh 
- [x] @sporejack

**Comment by Paul4912** [comment]
https://github.com/mycelium-ethereum/tracer-index-contracts/pull/11

heres link to it

**Comment by mynameuhh** [comment]
Made high review because this is blocking 0xCurry and his work on Indices

**Comment by nisdo** [comment]
Removing the `triage` label since I believe our focus on it so far, and the need for @sumermalhotra to get this feedback urgently validates the `high priority` label attached to it.

**Comment by sumermalhotra** [comment]
@nisdo Have already got a bunch of comments which have been extremely helpful. Still unsure what the best way of handling access specifiers, etc. are for functions defined within these contracts. 

Also, wanted to enquire if we're good to merge? @mynameuhh @sporejack @Paul4912

**Comment by mynameuhh** [comment]
@sumermalhotra It looks like a lot of the requested changes haven't been addressed yet.
e.g. [this one](https://github.com/mycelium-ethereum/tracer-index-contracts/pull/11/files#r759659821), among others.

**Comment by sporejack** [comment]
I think we have a pretty well-reasoned argument that this is done on our end (despite the changes not being applied upstream).
