### ISSUE TITLE
User Story: Testnets

### ISSUE THREAD

**Issue by issy-fleming** [tracer-protocol/perpetual-pools-contracts#227]
As a Financial Engineer	
I want the smart contracts deployed to a functional testnet 					
so that I can model economic behaviours of the system

**Comment by issy-fleming** [comment]
**Scenario 1**	
GIVEN	I have developed a model for system performance	
WHEN	I access the sythetic environment	
THEN	I want to manipulate the oracle price 	
AND	Collect data on the performance of the pools

**Comment by sporejack** [comment]
Related: #223

**Comment by issy-fleming** [comment]
This is no longer relevant to RnD
