### ISSUE TITLE
User Story: Trade Ledger

### ISSUE THREAD

**Issue by issy-fleming** [tracer-protocol/perpetual-pools-contracts#243]
Link to #229 

As a financial engineer
I want to execute predefined time and volume trades 
So that I can test my hypotheses for system performance given trade volume changes

**Comment by mynameuhh** [comment]
Could you provide clarity on this please?

Is this proposing a trade simulation or backtesting app? Or a bot that executes specified trades on a DEX (or a commit on pools)?

I'm not entirely sure but this doesn't sound like a smart contract change.

**Comment by nisdo** [comment]
Output would be a python script that models a series of trades over time. The purpose is for back-testing.

**Comment by nisdo** [comment]
Let's try moving this to a discussion thread
