### ISSUE TITLE
Deploy Oraclewrapper for EUR/USD Pool

### ISSUE THREAD

**Issue by nisdo** [tracer-protocol/perpetual-pools-contracts#245]
Subtask of #241 

- Get the underlying oracle addresses for EUR/USD Pool
- Deploy the oracl wrapper using these

**Comment by nisdo** [comment]
Consensus T-shirt size estimate: Small

**Comment by mynameuhh** [comment]
https://arbiscan.io/address/0x46cc327A9613BA67b74900714FE9B14fCF0e80AB#readContract
