### ISSUE TITLE
Pass `poolKeeper` and `autoClaim` as constructor arguments to the `PoolFactory`

### ISSUE THREAD

**Issue by mynameuhh** [tracer-protocol/perpetual-pools-contracts#258]
At the moment, you have to set `poolKeeper` and `autoClaim` in two other separate steps after you deploy the `PoolFactory`. This doesn't make sense and you may as well set the m in the constructor.

Also update the deployment scripts (deploy poolKeeper and autoClaim before deploying poolFactory)

**Comment by sporejack** [comment]
Closed by #256 @mynameuhh ?

**Comment by mynameuhh** [comment]
No, this is not added as part of that PR

**Comment by sporejack** [comment]
Sketch of solution:

 - [ ] Add `poolKeeper` to constructor parameters for `PoolFactory`
 - [ ] Add `autoClaim` to constructor parameters for `PoolFactory`
 - [ ] Update deployment scripts accordingly
     - [ ] Add new parameters
     - [ ] Remove (now-redundant) calls to their respective setters

**Comment by 0xhrithik** [comment]
Cannot be resolved because of circular dependency in poolFactory.

**Comment by 0xhrithik** [comment]
Cannot pass poolKeeper and autoclaim contracts in as constructor parameters to the PoolFactory because those two contracts require the pool factory as a constructor parameter resulting in a circular dependency
