### ISSUE TITLE
Deploy V1 to Arbitrum Rinkeby (to be used for a multisig deployment)

### ISSUE THREAD

**Issue by mynameuhh** [tracer-protocol/perpetual-pools-contracts#263]
Related to #262 
Blocks #264

We want a deployment of V1 contracts on Arbitrum Rinkeby that will be owned by a testnet multisig to replicate the current Mainnet deployment.

Steps
- [x] Deploy V1 contracts with any basic market to start it off (market doesn't matter - can be using test oracles)

**Comment by mynameuhh** [comment]
This doesn't require code verification on Etherscan.

**Comment by nisdo** [comment]
Good first task of @0xhrithik
