### ISSUE TITLE
Add SMA Oracle to Poolsv2 Deploy Script

### ISSUE THREAD

**Issue by Paul4912** [tracer-protocol/perpetual-pools-contracts#269]
Separating this out because there are additional changes that need to be done. 

SMA Oracle uses getPrice() function on oracle instead of latestRoundData() which our spot oracles uses. 

Need to change this to make deploy script work with SMA oracle then deploy pool associated with it.

**Comment by sporejack** [comment]
@Paul4912 mentioned in Discord that this may be redundant now.
