### ISSUE TITLE
Add ExecuteCommit event

### ISSUE THREAD

**Issue by mynameuhh** [tracer-protocol/perpetual-pools-contracts#294]
This should be emitted and emit mintAmount / collateralReturned (depending on mint or burn).

There will probably need to be different event definitions and multiple event emissions for the different commit types.

**Comment by ScaredIbis** [comment]
I would love if this event contained the following

- userAddress
- commitType
- inputAmount
- outputAmount

**Comment by ScaredIbis** [comment]
I looked through the code and couldn't really see a nice way to add this event, the following changes should be easier for you and still give me what I need

- add `appropriateUpdateIntervalId` to `CreateCommit` event
- add `CommitsExecuted(uint updateIntervalId)` to `PoolCommitter.executeCommitments`

I then plan to use `priceHistory[commit.appropriateUpdateInterval]` to figure out what price the commit would get executed at.
