### ISSUE TITLE
`SMAOracle` reverts on insufficient price data rendering deployment difficult

### ISSUE THREAD

**Issue by sporejack** [tracer-protocol/perpetual-pools-contracts#299]
# Description 
Currently, `SMAOracle` disallows polling when the number of observed prices in the backing store (i.e., `PriceObserver::length`) is less than the specified number of sampling periods to smooth over. This makes sense mathematically, but leaves us in a tricky situation with respect to deployments of the contracts. 

One possible solution (and arguably the most graceful) is to smooth *progressively* -- i.e., use a monotonically-increasing number of sampling periods until we have sufficient price observations in the backing store.

**Comment by greenbookwebb** [comment]
@sporejack 

This is the problem at market intialisaiton, correct?

I think there's two options:
1) The one you suggested above^;
2) or we go and retroactively collect the price observations from before the wrapper was deployed.

Am I correct in saying that (2) is possible, or are you saying this is a situation where the historical prices don't exist categorically.

**Comment by mynameuhh** [comment]
@greenbookwebb 2 is possible finnicky and requires a trusted entity to enter those prices.

**Comment by greenbookwebb** [comment]
Okay, well let's do (1) then. Definitely agree that this seems the best solution all-around
